In [1]:
import numpy as np 
matrix_size = 7
f = open("data/s.dat", 'r')
a = f.readlines()
s_mat = np.zeros((matrix_size, matrix_size))
for i in range(len(a)):
    a[i] = a[i].split()
    x,y,val = int(a[i][0]), int(a[i][1]), float(a[i][2])
    s_mat[x-1][y-1] = val 
    if x!=y: s_mat[y-1][x-1] = val 

eigenvalues, eigenvectors = np.linalg.eig(s_mat)
print("eigenvalues", eigenvalues)
print("eigenvectors", eigenvectors)

eigenvalues [1.76168822 0.43422215 1.10010419 0.88574533 0.51876465 1.29947547
 1.        ]
eigenvectors [[-2.34519160e-01 -2.28285695e-01 -6.46555592e-01 -6.89095256e-01
  -7.32372344e-16  2.68223379e-16  0.00000000e+00]
 [-5.89357288e-01  6.86047834e-01 -3.24108012e-01  2.77399265e-01
   2.00920769e-15  5.09836907e-16  0.00000000e+00]
 [ 2.11824889e-16 -4.19430552e-16 -6.25907161e-16  6.54128396e-16
   6.19349122e-01 -7.85115702e-01  0.00000000e+00]
 [-2.80518958e-01  3.20745209e-01  6.54330912e-01 -6.24726086e-01
   1.43284564e-15 -6.68070480e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [-5.09395654e-01 -4.32635251e-01  1.56158447e-01  1.70168583e-01
  -5.55160637e-01 -4.37945964e-01  0.00000000e+00]
 [-5.09395654e-01 -4.32635251e-01  1.56158447e-01  1.70168583e-01
   5.55160637e-01  4.37945964e-01  0.00000000e+00]]


In [2]:
# verify Av = λv
# ith column of v is a eignvector corresponds to the i-th term in eigenvalue

v = eigenvectors[:,0]
lam = eigenvalues[0]
print(np.dot(s_mat, v))
print(lam * v)

[-4.13149642e-01 -1.03826379e+00  4.44089210e-16 -4.94186943e-01
  0.00000000e+00 -8.97396322e-01 -8.97396322e-01]
[-4.13149642e-01 -1.03826379e+00  3.73169411e-16 -4.94186943e-01
  0.00000000e+00 -8.97396322e-01 -8.97396322e-01]


In [3]:
lam_inv_sqrt = np.linalg.inv(np.sqrt(np.diag(eigenvalues)))
k = eigenvectors@(lam_inv_sqrt)@eigenvectors.T
k

array([[ 1.02363458e+00, -1.36854681e-01, -7.99740794e-16,
        -7.48725613e-03,  0.00000000e+00,  1.90278865e-02,
         1.90278865e-02],
       [-1.36854681e-01,  1.15786320e+00,  1.23206934e-15,
         7.21600680e-02,  0.00000000e+00, -2.22332556e-01,
        -2.22332556e-01],
       [-7.99740794e-16,  1.23206934e-15,  1.07331475e+00,
         6.18624993e-16,  0.00000000e+00, -1.75758305e-01,
         1.75758305e-01],
       [-7.48725613e-03,  7.21600680e-02,  6.18624993e-16,
         1.03830505e+00,  0.00000000e+00, -1.18462559e-01,
        -1.18462559e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 1.90278865e-02, -2.22332556e-01, -1.75758305e-01,
        -1.18462559e-01,  0.00000000e+00,  1.12972342e+00,
        -6.25975108e-02],
       [ 1.90278865e-02, -2.22332556e-01,  1.75758305e-01,
        -1.18462559e-01,  0.00000000e+00, -6.25975108e-02,
         1.1297234

In [4]:
np.diag(eigenvalues)

array([[1.76168822, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.43422215, 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 1.10010419, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.88574533, 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.51876465,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.29947547, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        ]])

In [7]:
import pickle as pkl
eri = pkl.load(open("eri.pkl", "rb"))
print(len(eri), len(eri[0]), len(eri[0][0]), len(eri[0][0][0]))

7 7 7 7


In [13]:
print(eri[3][3][3])

[-7.39153187e-18 -2.63322412e-17  0.00000000e+00  8.80159093e-01
  0.00000000e+00  1.35497737e-01  1.35497737e-01]


In [15]:
print(eri[-1][-1][-1][-1])

0.7746059439198978


In [3]:
import numpy as np
s_mat = np.zeros((7, 7))
s_mat[2][5] = 1
t_mat = np.ones((7, 7))
s_mat / t_mat

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
nocc = 7
mo_energy = 

def eng_mp2_corr(self):
    # Output: (Restricted) MP2 correlation energy
    nocc, e = nocc, mo_energy
    eri_iajb = self.eri_mo[:nocc, nocc:, :nocc, nocc:]
    D_iajb = e[:nocc, None, None, None] - e[None, nocc:, None, None] + e[None, None, :nocc, None] - e[None, None, None, nocc:]
    return (eri_iajb * (2 * eri_iajb - eri_iajb.swapaxes(-1, -3)) / D_iajb).sum()